import type { Translations } from './types';

export const en: Translations = {
  /* ── Global chrome ─────────────────────────────────────────────── */
  skip_to_main:    'Skip to main content',
  nav_wordmark_aria: 'Mnemosyne Engine — home',
  nav_main_aria:   'Main navigation',
  nav_gilgamesh:   'Gilgamesh',
  nav_iliad:       'Iliad',
  nav_parallels:   'Parallels',
  locale_group_aria: 'Language: English / Russian',
  locale_en:       'EN',
  locale_ru:       'RU',

  /* ── Footer ────────────────────────────────────────────────────── */
  footer_name:       'MNEMOSYNE ENGINE',
  footer_phase_main: 'Phase 1 · Gilgamesh + Iliad · EN + RU interface',
  footer_stmt_main:  'Reviewed AI-generated content is marked with the reviewer\'s name and date. Demo content is explicitly marked not scholar-reviewed. All claims carry an epistemic tier. Computationally-detected relationships are never shown publicly until confirmed by a scholar.',
  footer_stmt_short: 'Reviewed AI-generated content is marked with the reviewer\'s name and date. Demo content is explicitly marked not scholar-reviewed.',
  footer_about:      'About',
  footer_epistemic:  'Epistemic tiers',
  footer_contact:    'Contact',
  footer_nav_aria:   'Footer navigation',

  /* ── Epistemic tier labels ──────────────────────────────────────── */
  tier_documented:       '● DOCUMENTED',
  tier_reconstructed:    '◑ RECONSTRUCTED',
  tier_contested:        '◈ CONTESTED',
  tier_ai_reviewed:      '▲ AI-REVIEWED',
  tier_documented_desc:  'Primary source evidence; strong scholarly consensus.',
  tier_reconstructed_desc: 'Inferred from partial evidence; scholarly consensus with acknowledged gaps.',
  tier_contested_desc:   'Active scholarly debate; multiple valid positions remain.',
  tier_ai_reviewed_desc: 'AI-generated interpretation reviewed by a named scholar.',

  /* ── Landing page ───────────────────────────────────────────────── */
  hero_title:    'Humanity\'s great epics, navigable to their depths.',
  hero_subtitle: 'Six traditions. Every claim marked for what kind of evidence supports it.',
  active_traditions:     'Active traditions',
  forthcoming_traditions: 'Forthcoming traditions',
  tradition_mesopotamian: 'MESOPOTAMIAN',
  tradition_greek:        'GREEK',
  idx_title_gilgamesh:  'The Epic of Gilgamesh',
  idx_title_iliad:      'The Iliad',
  idx_gilgamesh_epoch:  'c. 2100–1200 BCE · Standard Babylonian Version',
  idx_iliad_epoch:      'c. 8th century BCE · Attributed to Homer · Dactylic hexameter',
  idx_gilgamesh_desc:   'The oldest surviving epic narrative. A king\'s search for immortality after the death of his companion. The earliest recorded flood story. The oldest question about whether a life can mean anything if it ends.',
  idx_iliad_desc:       '24 books. The Trojan War, the rage of Achilles, the death of Hector. The oldest surviving text of the Western literary tradition, composed in oral form before writing, committed to text in the 8th century BCE. The poem ends not with victory but with grief shared between enemies.',
  idx_gilgamesh_stats:  '6 tablets · 15 episodes · 1 confirmed cross-tradition parallel',
  idx_iliad_stats:      '6 books · 16 episodes · 1 confirmed cross-tradition parallel',
  enter_gilgamesh:      'Enter the Epic of Gilgamesh →',
  enter_iliad:          'Enter the Iliad →',
  about_platform:       'About the platform',
  idx_about_p1: 'Mnemosyne Engine is an explorable interface for the great epic traditions of the world. Every claim is marked for what kind of evidence supports it: primary source, scholarly inference, active scholarly debate, or AI-generated interpretation reviewed by a named scholar. You can read a plain-language summary or the original translation; zoom into scholarly debate or cross to another tradition\'s parallel passage. The depth you want is always one step away.',
  idx_about_p2: 'No claim is presented without its epistemic grounding. When a passage is actively contested among scholars, that contest is made visible — not resolved or hidden. When an interpretation was generated by AI and reviewed by a human expert, that provenance is disclosed at the top of every content block. The platform\'s promise is not completeness; it is honesty about what is known, what is inferred, and what remains in open debate.',

  /* ── Breadcrumb ─────────────────────────────────────────────────── */
  bc_home: 'Home',

  /* ── Tradition overview — Gilgamesh ─────────────────────────────── */
  trad_gilgamesh_epoch_full: 'c. 2100–1200 BCE · Standard Babylonian Version · Cuneiform · Oral-to-written tradition',
  trad_gilgamesh_desc_p1: 'The oldest surviving epic narrative. Gilgamesh, king of Uruk, is two-thirds god and one-third human — larger than life, and unable to come to terms with the human part. After the death of his companion Enkidu, Gilgamesh sets out to find the secret of eternal life. He does not find it. What he finds instead is the oldest recorded argument that a mortal life, fully lived, is enough.',
  trad_gilgamesh_desc_p2: 'The text survives in fragments across hundreds of clay tablets, found in libraries from Nineveh to Megiddo. The most complete version — the Standard Babylonian Version, assembled in the 12th century BCE by the scholar-priest Sîn-lēqi-unninni — is what we have here. Even the Standard Babylonian Version is not complete: dozens of passages survive only as lacunae, damage to the clay that no scholarship has bridged.',
  cross_tradition_link:   'Cross-tradition resonances in this epic →',
  trad_cross_tradition_sub: '1 confirmed parallel — the flood narrative appears in Babylonian and Biblical traditions',
  tablets_label:          'TABLETS',
  trad_tablet1_label:     'TABLET I',
  trad_tablet1_name:      'The Coming of Enkidu',
  trad_tablet1_desc:      'Gilgamesh, king of Uruk, tyrannizes his city. The gods create Enkidu — wild man of the steppe — to balance him. The two become inseparable companions.',
  trad_tablet1_ep:        '4 episodes',
  trad_tablet2_label:     'TABLET II',
  trad_tablet2_name:      'The Forest Journey',
  trad_tablet2_desc:      'Gilgamesh and Enkidu journey to the Cedar Forest to fight Humbaba, its monstrous guardian. The elders of Uruk are opposed; the two go anyway.',
  trad_tablet2_ep:        '3 episodes',
  trad_tablet3_label:     'TABLET III',
  trad_tablet3_name:      'The Bull of Heaven',
  trad_tablet3_desc:      'Ishtar seeks Gilgamesh\'s love; he refuses her with contemptuous precision. She sends the Bull of Heaven to destroy Uruk. Gilgamesh and Enkidu kill it.',
  trad_tablet3_ep:        '2 episodes',
  trad_tablet4_label:     'TABLET IV',
  trad_tablet4_name:      'The Death of Enkidu',
  trad_tablet4_desc:      'Enkidu falls ill as punishment for killing Humbaba and the Bull of Heaven. He dies after twelve days of suffering. Gilgamesh refuses to accept it.',
  trad_tablet4_ep:        '3 episodes',
  trad_tablet5_label:     'TABLET V',
  trad_tablet5_name:      'The Search for Immortality',
  trad_tablet5_desc:      'Devastated by grief, Gilgamesh abandons the city and sets out to find Utnapishtim — the one mortal granted eternal life — to learn his secret.',
  trad_tablet5_ep:        '3 episodes',
  trad_tablet11_label:    'TABLET XI',
  trad_tablet11_name:     'The Flood',
  trad_tablet11_desc:     'Utnapishtim tells Gilgamesh how he survived the great flood and was granted eternal life. The gods\' gift to one cannot be Gilgamesh\'s. The reckoning.',
  trad_tablet11_ep_parallel: '● 1 confirmed parallel',
  trad_tablet11_ep_count:  '3 episodes',

  /* ── Tablet hub — Tablet XI ──────────────────────────────────────── */
  tablet_hub_heading:     'TABLET XI',
  tablet_hub_subtitle:    'The Flood Tablet',
  tablet_hub_intro:       'The best-preserved tablet of the Standard Babylonian Version. Lines 1–196 contain the flood narrative; the rest records Utnapishtim\'s challenge and Gilgamesh\'s failure, followed by a coda added in the 12th century BCE by Sîn-lēqi-unninni. This is the tablet that first established the Gilgamesh epic\'s importance to modern scholarship when George Smith identified it in 1872.',
  tablet_hub_breadcrumb:  'Tablet XI',
  tablet_hub_nav_prev:    '← Tablet V · The Search for Immortality',
  tablet_hub_nav_next:    'Tablet XII · The Netherworld →',
  tablet_ep1_nas_confirm: '● 1 confirmed parallel',
  tab_hub_episodes_intro: 'The best-preserved tablet in the Standard Babylonian Version. The flood narrative occupies lines 1–196.',
  tab_ep1_name:           'The Flood',
  tab_ep1_desc:           'Utnapishtim\'s account of the great flood. The gods\' decision; Ea\'s warning; the building of the boat; seven days of rain; the birds sent out; the sacrifice; Enlil\'s judgment.',
  tab_ep2_name:           'Utnapishtim\'s Challenge',
  tab_ep2_desc:           'Stay awake for seven days. Gilgamesh fails immediately. Bread loaves mark each day of his sleep.',
  tab_ep3_name:           'The Plant of Immortality',
  tab_ep3_desc:           'Utnapishtim\'s wife intercedes. The plant of immortality is revealed. Gilgamesh dives for it; a serpent takes it; he returns to Uruk empty-handed.',
  episodes_label:         'EPISODES',

  /* ── Fragment reader — layer tabs ──────────────────────────────── */
  layer_surface:   '[ Surface ● ]',
  layer_narrated:  '[ Narrated ○ ]',
  layer_translated:'[ Translated ○ ]',
  layer_original:  '[ Original ○ ]',
  layer_scholaria: '[ Scholaria ○ ]',

  /* ── Fragment reader — NAS + copy ───────────────────────────────── */
  copy_btn:            'copy',
  copied_confirm:      'copied',
  sources_region_label:'Grounding sources',
  see_sources:         '[See sources]',
  hide_sources:        '[Hide sources]',

  /* ── Fragment reader — structure toggle ─────────────────────────── */
  show_structure: 'Show structure ▾',
  hide_structure: 'Hide structure ▲',

  /* ── Fragment reader — AI disclosure + demo marker ──────────────── */
  frag_ai_disclosure_lead: '▲ AI-generated summary · Reviewed by Dr. A. Kovacs · 2026-04-18',
  frag_nas_tag_doc:        ' [● Documented]',
  demo_content_marker:     'AI-generated demo content — not scholar-reviewed',
  honest_absence_narrated: 'The narrated layer for this episode is not yet available.',
  honest_absence_original: 'Original-language text for this episode is not yet available.',

  /* ── Fragment reader — badge popup bodies ───────────────────────── */
  frag_badge_ai_pop_p1:     'AI-generated and reviewed by a named scholar before publication. Interpretive content; disclosed provenance.',
  frag_badge_ai_pop_p2:     'This summary was generated by a language model and reviewed for accuracy and scholarly appropriateness by Dr. A. Kovacs (2026-04-18).',
  frag_badge_trans_pop_p1:  'Primary source; strong scholarly consensus. This is an attested passage from R. Campbell Thompson\'s 1930 translation — a public-domain text with established scholarly standing.',
  frag_badge_schol_pop_p1:  'Multiple epistemic tiers are present in this layer. Manuscript attestation is Documented; the question of the interpolated coda is actively Contested among scholars.',
  frag_badge_narr_pop_p1:   'Scholarly narrative synthesizing current academic understanding of this episode, with quoted passages from the translated text. AI-generated demo content — not scholar-reviewed.',
  frag_badge_orig_pop_p1:   'Source text in original language (Standard Babylonian Akkadian transliteration, after George 2003). AI-assembled from published editions — not scholar-reviewed.',

  /* ── Fragment reader — tier badge labels ────────────────────────── */
  badge_documented:   '● DOCUMENTED',
  badge_reconstructed:'◑ RECONSTRUCTED',
  badge_contested:    '◈ CONTESTED',
  badge_ai_reviewed:  '▲ AI-REVIEWED',

  /* ── Fragment reader — Flood episode ────────────────────────────── */
  frag_flood_title:    'THE FLOOD EPISODE',
  frag_flood_subtitle: 'Tablet XI of the Epic of Gilgamesh',
  frag_surf_flood_p1:  'Gilgamesh, stricken by the death of Enkidu and unable to accept his own mortality, seeks out Utnapishtim — the one mortal who has been granted eternal life by the gods. Utnapishtim lives beyond the waters of death, at the ends of the earth. Gilgamesh crosses them.',
  frag_surf_flood_p2:  'At the edge of the world, Utnapishtim tells Gilgamesh a secret: he survived the great flood. The gods had decided to destroy all life. But the god Ea, bound by oath not to warn any human directly, whispered the decision through the walls of a reed house. Utnapishtim heard. He built a boat. He loaded his family, his possessions, and every living creature onto it. The flood came.',
  frag_surf_flood_p3:  'The waters covered the mountains. After seven days the flood subsided. Utnapishtim sent out birds — first a dove, then a swallow, then a raven — to find land. The raven did not return. He disembarked and made sacrifice. The gods, who had not eaten since the flood began, gathered over the offering.',
  frag_surf_flood_p4:  'The goddess Ishtar swore an oath on her lapis lazuli necklace: she would remember these days. The god Enlil, who had decreed the flood, was rebuked by Ea for his disproportionate judgment. As recompense, Enlil granted Utnapishtim and his wife the gift of eternal life and placed them at the mouth of the rivers, at the ends of the earth, where they remain.',
  frag_nav_tablet_hub: '← Tablet XI episodes',
  frag_nav_next_sleep: 'Utnapishtim\'s Challenge →',

  /* ── Fragment reader — parallel strip ───────────────────────────── */
  parallel_strip_heading: 'Structural resonance in another tradition',
  parallel_flood_body:    'Both traditions depict a divine judgment by flood, a chosen survivor warned through an indirect channel, and birds sent to find dry land. They diverge in what the survivor receives: immortality vs. covenant.',
  parallel_type_shared:   'Type: Shared human condition — not a shared source',
  read_this_parallel:     'Read this parallel →',

  /* ── Fragment reader — Scholaria headings ───────────────────────── */
  schol_manuscript_status: 'MANUSCRIPT STATUS',
  schol_textual_history:   'TEXTUAL HISTORY',
  schol_key_variants:      'KEY MANUSCRIPT VARIANTS',
  schol_scholarship_cited: 'SCHOLARSHIP CITED',

  /* ── Common UI ──────────────────────────────────────────────────── */
  in_preparation: 'In preparation',
  phase2_badge:   'Phase 2',
  close_x:        'close ×',
};
