import type { Translations } from './types';

export const en: Translations = {
  /* ── Global chrome ─────────────────────────────────────────────── */
  skip_to_main:    'Skip to main content',
  nav_wordmark_aria: 'Mnemosyne Engine — home',
  nav_main_aria:   'Main navigation',
  nav_gilgamesh:   'Gilgamesh',
  nav_iliad:       'Iliad',
  nav_parallels:   'Parallels',
  locale_group_aria: 'Language: English / Russian',
  locale_en:       'EN',
  locale_ru:       'RU',

  /* ── Footer ────────────────────────────────────────────────────── */
  footer_name:       'MNEMOSYNE ENGINE',
  footer_phase_main: 'Phase 1 · Gilgamesh + Iliad · EN + RU interface',
  footer_stmt_main:  'Reviewed AI-generated content is marked with the reviewer\'s name and date. Demo content is explicitly marked not scholar-reviewed. All claims carry an epistemic tier. Computationally-detected relationships are never shown publicly until confirmed by a scholar.',
  footer_stmt_short: 'Reviewed AI-generated content is marked with the reviewer\'s name and date. Demo content is explicitly marked not scholar-reviewed.',
  footer_about:      'About',
  footer_epistemic:  'Epistemic tiers',
  footer_contact:    'Contact',
  footer_nav_aria:   'Footer navigation',

  /* ── Epistemic tier labels ──────────────────────────────────────── */
  tier_documented:       '● DOCUMENTED',
  tier_reconstructed:    '◑ RECONSTRUCTED',
  tier_contested:        '◈ CONTESTED',
  tier_ai_reviewed:      '▲ AI-REVIEWED',
  tier_documented_desc:  'Primary source evidence; strong scholarly consensus.',
  tier_reconstructed_desc: 'Inferred from partial evidence; scholarly consensus with acknowledged gaps.',
  tier_contested_desc:   'Active scholarly debate; multiple valid positions remain.',
  tier_ai_reviewed_desc: 'AI-generated interpretation reviewed by a named scholar.',

  /* ── Landing page ───────────────────────────────────────────────── */
  hero_title:    'Humanity\'s great epics, navigable to their depths.',
  hero_subtitle: 'Six traditions. Every claim marked for what kind of evidence supports it.',
  active_traditions:     'Active traditions',
  forthcoming_traditions: 'Forthcoming traditions',
  tradition_mesopotamian: 'MESOPOTAMIAN',
  tradition_greek:        'GREEK',
  idx_title_gilgamesh:  'The Epic of Gilgamesh',
  idx_title_iliad:      'The Iliad',
  idx_gilgamesh_epoch:  'c. 2100–1200 BCE · Standard Babylonian Version',
  idx_iliad_epoch:      'c. 8th century BCE · Attributed to Homer · Dactylic hexameter',
  idx_gilgamesh_desc:   'The oldest surviving epic narrative. A king\'s search for immortality after the death of his companion. The earliest recorded flood story. The oldest question about whether a life can mean anything if it ends.',
  idx_iliad_desc:       '24 books. The Trojan War, the rage of Achilles, the death of Hector. The oldest surviving text of the Western literary tradition, composed in oral form before writing, committed to text in the 8th century BCE. The poem ends not with victory but with grief shared between enemies.',
  idx_gilgamesh_stats:  '6 tablets · 15 episodes · 1 confirmed cross-tradition parallel',
  idx_iliad_stats:      '6 books · 16 episodes · 1 confirmed cross-tradition parallel',
  enter_gilgamesh:      'Enter the Epic of Gilgamesh →',
  enter_iliad:          'Enter the Iliad →',
  about_platform:       'About the platform',
  idx_about_p1: 'Mnemosyne Engine is an explorable interface for the great epic traditions of the world. Every claim is marked for what kind of evidence supports it: primary source, scholarly inference, active scholarly debate, or AI-generated interpretation reviewed by a named scholar. You can read a plain-language summary or the original translation; zoom into scholarly debate or cross to another tradition\'s parallel passage. The depth you want is always one step away.',
  idx_about_p2: 'No claim is presented without its epistemic grounding. When a passage is actively contested among scholars, that contest is made visible — not resolved or hidden. When an interpretation was generated by AI and reviewed by a human expert, that provenance is disclosed at the top of every content block. The platform\'s promise is not completeness; it is honesty about what is known, what is inferred, and what remains in open debate.',

  /* ── Common UI ──────────────────────────────────────────────────── */
  in_preparation: 'In preparation',
  phase2_badge:   'Phase 2',
  close_x:        'close ×',
};
